scriptsVSdata = {
    AtmosphereTemp : null,
    AreaBasic : null,
    AreaStack : null,
    AreaRange : ['AreaRange'],
    AreaSpine : null,
    BarBasic : null,
    BarStack : null,
    BoxPlot : null,
    Bubble : null,
    ColumnBasic: null,
    ColumnRotated: null,
    ColumnStacked: null,
    ColumnRange: null,
    Combo1: null,
    DynamicClickAdd : null,
    DynamicUpdate : null,
    LineBasic : null,
    LineLabels : null,
    LineLogAxis : null,
    LineTime : ['timeData'],
    PieBase : null,
    PieDonut : null,
    PieDrillDown : ['DrillPie'],
    PieLegend : null,
    PolarSpider : null,
    Pyramid : null
};

